### ISSUE TITLE
reported translation problem

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-nno-nob#1]
Reported via apertium-contact address:

> Hei, jeg fant en feil når jeg oversetter fra nynorsk til bokmål. Det skulle egentlig stå på bokmål valgt ikke veltet. Håper at det kan forbedre nett siden.

**Comment by unhammer** [comment]
fixed in apertium-nno ca9b30ad672d65b34c6d58aeb2de32148995bea1
https://github.com/apertium/apertium-nno/blob/master/apertium-nno.nno.rlx#L803
